#!/usr/bin/env bash

# Initialize our own variables:
machines="1"
release_mode="Release"

cd build
module load cmake
module load intel/mpi/64
cmake . > /dev/null 2>&1

usage() {
    echo "Usage: $0 [-n <machines>] BINARY" 1>&2;
    exit 1;
}

while getopts "h?n:d" opt; do
    case "$opt" in
    h|\?)
        usage
        ;;
    n)
        machines=${OPTARG}
        ;;
    d)
        release_mode="Debug"
        ;;
    \? )
        echo "Invalid option: $OPTARG" 1>&2
        ;;
    : )
        echo "Invalid option: $OPTARG requires an argument" 1>&2
        ;;
    esac
done
shift $((OPTIND-1))
binary=${1:-all}
shift

echo -e "\e[32mBuilding ${binary}\e[0m"
cmake -DCMAKE_BUILD_TYPE=${release_mode} ..
make ${binary}
rc=$?; if [[ ${rc} != 0 ]] || [[ ${binary} == "all" ]]; then exit ${rc}; fi
echo -e "\e[32mRunning ${binary} on ${machines} machine(s)\e[0m"
srun --partition=amd-longq -N ${machines} --mpi=pmi2 ${binary} ${@}

cd ..
